/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecemergency.capaPresentacion.Principal;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import tecemergency.capaLogica.Logica.EnumColor;
import tecemergency.capaLogica.Logica.Ficha;
import tecemergency.capaLogica.Logica.GestionEmergencias;
import tecemergency.capaLogica.Logica.GestionPacientes;
import tecemergency.capaLogica.Logica.GestionUrgencias;
import tecemergency.capaLogica.Logica.ModuloEmergencias;
import tecemergency.capaLogica.Logica.ModuloUrgencias;
import tecemergency.capaLogica.Logica.Patient;
import tecemergency.capaLogica.estructuras.Lista;
import tecemergency.capaLogica.estructuras.Nodo;
import tecemergency.capaLogica.estructuras.NodoD;
import tecemergency.capaLogica.estructuras.NodoS;
import tecemergencyl.capaLogica.utils.ModeladorTablas;

/**
 *
 * @author sebas
 */
public class Principal extends javax.swing.JDialog {
    VentanaConfig ventConfig;
    private GestionPacientes listaPacientes;
    private GestionUrgencias urgencias;
    private GestionEmergencias emergencias;
    private static int numeroUrgencias;
    private static int numeroEmergencias;

    public static int getNumeroUrgencias() {
        return numeroUrgencias;
    }

    public static void setNumeroUrgencias(int numeroUrgencias) {
        Principal.numeroUrgencias = numeroUrgencias;
    }

    public static int getNumeroEmergencias() {
        return numeroEmergencias;
    }

    public static void setNumeroEmergencias(int numeroEmergencias) {
        Principal.numeroEmergencias = numeroEmergencias;
    }
    
    

    public GestionEmergencias getEmergencias() {
        return emergencias;
    }

    public void setEmergencias(GestionEmergencias emergencias) {
        this.emergencias = emergencias;
    }

    public GestionUrgencias getUrgencias() {
        return urgencias;
    }

    public void setUrgencias(GestionUrgencias urgencias) {
        this.urgencias = urgencias;
    }
    
    

    public VentanaConfig getVentConfig() {
        return ventConfig;
    }

    public void setVentConfig(VentanaConfig ventConfig) {
        this.ventConfig = ventConfig;
    }

    public GestionPacientes getListaPacientes() {
        return listaPacientes;
    }

    public void setListaPacientes(GestionPacientes listaPacientes) {
        this.listaPacientes = listaPacientes;
    }   

    /**
     * Creates new form VentPrincipal
     */
    public Principal(java.awt.Dialog parent, boolean modal, VentanaConfig ventConfig) {
        super(parent, modal);
        initComponents();
        this.ventConfig = ventConfig;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buttonGroupTipoPadecimiento = new javax.swing.ButtonGroup();
        buttonGroupPrioridadColores = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonInfartoPaciente = new javax.swing.JRadioButton();
        jRadioButtonPérdidasangrePaciente = new javax.swing.JRadioButton();
        jRadioButtonPartoPaciente = new javax.swing.JRadioButton();
        jRadioButtonEstomacalPaciente = new javax.swing.JRadioButton();
        jTextFieldNombrePaciente = new javax.swing.JTextField();
        jTextFieldNacimientoPaciente = new javax.swing.JTextField();
        jTextFieldDetallePadePaciente = new javax.swing.JTextField();
        jButtonRegistrarsePaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaEspera = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonQuebraduraPaciente = new javax.swing.JRadioButton();
        jRadioButtonOtroPaciente = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacientesUrgencias = new javax.swing.JTable();
        jButtonAtenderUrgencias = new javax.swing.JButton();
        jButtonLiberarAtenderUrgencias = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePacientesEmergencias = new javax.swing.JTable();
        jButtonAtenderEmergencias = new javax.swing.JButton();
        jButtonLiberarAtenderEmergencias = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEgresos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonPrioridadVerde = new javax.swing.JRadioButton();
        jRadioButtonPrioridadAmarillo = new javax.swing.JRadioButton();
        jRadioButtonPrioridadRojo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldNumeroModificarConsultoriosUrgencias = new javax.swing.JTextField();
        jTextFieldNumeroModificarConsultoriosEmergencias = new javax.swing.JTextField();
        jTextFieldNumeroModificarConsultorios = new javax.swing.JTextField();
        jButtonModificarUrgencias = new javax.swing.JButton();
        jButtonModificarEmergencias = new javax.swing.JButton();
        jButtonModificarEgresos = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelNumeroUrgencias = new javax.swing.JLabel();
        jLabelNumerosEmergencias = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        jLabel1.setText("TEC Emergencias");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Registro de Ingresos:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setText("Detalles de padecimiento:");

        jLabel6.setText("Tipo de padecimiento:");

        buttonGroupTipoPadecimiento.add(jRadioButtonInfartoPaciente);
        jRadioButtonInfartoPaciente.setText("Infarto");

        buttonGroupTipoPadecimiento.add(jRadioButtonPérdidasangrePaciente);
        jRadioButtonPérdidasangrePaciente.setText("Pérdida sangre por herida");

        buttonGroupTipoPadecimiento.add(jRadioButtonPartoPaciente);
        jRadioButtonPartoPaciente.setText("Parto");

        buttonGroupTipoPadecimiento.add(jRadioButtonEstomacalPaciente);
        jRadioButtonEstomacalPaciente.setText("Dolor estomacal");

        jTextFieldDetallePadePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDetallePadePacienteActionPerformed(evt);
            }
        });

        jButtonRegistrarsePaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegistrarsePaciente.setText("Registrarse");
        jButtonRegistrarsePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarsePacienteActionPerformed(evt);
            }
        });

        jTableListaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListaEspera);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Pacientes registrados( Lista de Espera)");

        buttonGroupTipoPadecimiento.add(jRadioButtonQuebraduraPaciente);
        jRadioButtonQuebraduraPaciente.setText("Quebradura");

        buttonGroupTipoPadecimiento.add(jRadioButtonOtroPaciente);
        jRadioButtonOtroPaciente.setText("Otro");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("Módulo de Urgencias:");

        jTablePacientesUrgencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePacientesUrgencias);

        jButtonAtenderUrgencias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAtenderUrgencias.setText("Atender");

        jButtonLiberarAtenderUrgencias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLiberarAtenderUrgencias.setText("Liberar y atender");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("Módulo de Emergencias:");

        jTablePacientesEmergencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePacientesEmergencias);

        jButtonAtenderEmergencias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAtenderEmergencias.setText("Atender");

        jButtonLiberarAtenderEmergencias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLiberarAtenderEmergencias.setText("Liberar y atender");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Administración:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel11.setText("Módulo de Egresos:");

        jTableEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableEgresos);

        jLabel12.setText("Prioridad:");

        buttonGroupPrioridadColores.add(jRadioButtonPrioridadVerde);
        jRadioButtonPrioridadVerde.setText("Verde");

        buttonGroupPrioridadColores.add(jRadioButtonPrioridadAmarillo);
        jRadioButtonPrioridadAmarillo.setText("Amarillo");

        buttonGroupPrioridadColores.add(jRadioButtonPrioridadRojo);
        jRadioButtonPrioridadRojo.setText("Rojo");
        jRadioButtonPrioridadRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrioridadRojoActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado de consultorios:");

        jLabel14.setText("Cantidad de pacientes en Urgencias");

        jLabel15.setText("Cantidad de pacientes en Emergencias:");

        jLabel16.setText("Proximo a atender en Urgencias:");

        jLabel17.setText("Proximo a atender en Emergencias:");

        jLabel18.setText("Numeros de fichas en Urgencias:");

        jLabel19.setText("Numeros de fichas en Emergencias:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Administración de consultorios:");

        jLabel21.setText("Modificar número de consultorios del Módulo de Urgencias:");

        jLabel22.setText("Modificar número de consultorios del Módulo de Emergencias:");

        jLabel23.setText("Modificar número de consultorios del Módulo de Egresos:");

        jButtonModificarUrgencias.setText("Modificar Urgencias");

        jButtonModificarEmergencias.setText("Modificar Emergencias");

        jButtonModificarEgresos.setText("Modificar Egresos");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Estadísticas:");

        jLabel25.setText("Tiempo promedio de espera por condición de paciente Urgencias:");

        jLabel26.setText("Tiempo promedio de espera por condición de paciente Emergencias:");

        jLabel27.setText("Tiempo promedio de espera de cola de egresos:");

        jLabel28.setText("Total de pacientes atendidos Rojos:");

        jLabel29.setText("Total de pacientes atendidos Verdes:");

        jLabel30.setText("Total de pacientes atendidos Amarillos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(227, 227, 227)
                        .addComponent(jLabel8)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNacimientoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldDetallePadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButtonInfartoPaciente)
                                .addGap(44, 44, 44)
                                .addComponent(jRadioButtonPartoPaciente)
                                .addGap(56, 56, 56)
                                .addComponent(jRadioButtonPérdidasangrePaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButtonPrioridadVerde)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButtonPrioridadAmarillo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonPrioridadRojo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jButtonRegistrarsePaciente))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jRadioButtonEstomacalPaciente)
                                    .addGap(2, 2, 2)
                                    .addComponent(jRadioButtonQuebraduraPaciente)
                                    .addGap(24, 24, 24)
                                    .addComponent(jRadioButtonOtroPaciente))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonAtenderUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jButtonLiberarAtenderUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAtenderEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButtonLiberarAtenderEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNumerosEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(145, 145, 145)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel30)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(252, 252, 252)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel20)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldNumeroModificarConsultoriosUrgencias))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNumeroModificarConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNumeroModificarConsultoriosEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNumeroUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonModificarUrgencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModificarEmergencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModificarEgresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAtenderEmergencias)
                            .addComponent(jButtonLiberarAtenderEmergencias))
                        .addGap(103, 103, 103)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldNumeroModificarConsultoriosUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarUrgencias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldNumeroModificarConsultoriosEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarEmergencias))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldNumeroModificarConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarEgresos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addComponent(jTextFieldNacimientoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldDetallePadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonInfartoPaciente)
                                    .addComponent(jRadioButtonPartoPaciente)
                                    .addComponent(jRadioButtonPérdidasangrePaciente))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEstomacalPaciente)
                                    .addComponent(jRadioButtonQuebraduraPaciente)
                                    .addComponent(jRadioButtonOtroPaciente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonPrioridadVerde)
                                    .addComponent(jRadioButtonPrioridadAmarillo)
                                    .addComponent(jRadioButtonPrioridadRojo))
                                .addGap(27, 27, 27)
                                .addComponent(jButtonRegistrarsePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAtenderUrgencias)
                                    .addComponent(jButtonLiberarAtenderUrgencias))
                                .addGap(79, 79, 79)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabelNumeroUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabelNumerosEmergencias, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDetallePadePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDetallePadePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDetallePadePacienteActionPerformed

    private void jButtonRegistrarsePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarsePacienteActionPerformed


/////////////////////Clasifica el paciente////////////////////////////////////
        String nombre, fechaNacimiento,detalle;
        Ficha ficha;
        String enfermedad = null;
        if (jRadioButtonEstomacalPaciente.isSelected()){
            enfermedad = "D";
        }
        if (jRadioButtonInfartoPaciente.isSelected()){
            enfermedad = "I";
        }
        if (jRadioButtonOtroPaciente.isSelected()){
            enfermedad = "O";
        }
        if (jRadioButtonPartoPaciente.isSelected()){
            enfermedad = "P";
        }if (jRadioButtonPérdidasangrePaciente.isSelected()){
            enfermedad = "H";
        }if (jRadioButtonQuebraduraPaciente.isSelected()){
            enfermedad = "Q";
        }
        
        Ficha nuevaficha = new Ficha(EnumColor.YELLOW, enfermedad,0);
        if (jRadioButtonPrioridadVerde.isSelected()){
            numeroUrgencias = numeroUrgencias+1;
            nuevaficha.setState(EnumColor.GREEN);
            nuevaficha.setPadecimiento(enfermedad);
            nuevaficha.setNumero(numeroUrgencias);
        }if (jRadioButtonPrioridadAmarillo.isSelected()){
            numeroUrgencias = numeroUrgencias+1;
           nuevaficha.setState(EnumColor.YELLOW);
           nuevaficha.setPadecimiento(enfermedad);
           nuevaficha.setNumero(numeroUrgencias);
        }else if (jRadioButtonPrioridadRojo.isSelected()){
          numeroEmergencias = numeroEmergencias+1;
          nuevaficha.setState(EnumColor.RED);
          nuevaficha.setPadecimiento(enfermedad);
          nuevaficha.setNumero(numeroEmergencias);
        }
        
        
        System.out.println(enfermedad);
        nombre = jTextFieldNombrePaciente.getText();
        fechaNacimiento = jTextFieldNacimientoPaciente.getText();
        detalle = jTextFieldDetallePadePaciente.getText();
        Patient nuevoPaciente = new Patient(nombre,fechaNacimiento,detalle,enfermedad);
        nuevoPaciente.setFicha(nuevaficha);
        System.out.println(nuevaficha.toString());
        JOptionPane.showMessageDialog(this, "Código de boleto: "+nuevaficha.getState().getColorCode()+"-"+nuevaficha.getPadecimiento()+"-"+nuevaficha.getNumero());
        //this.listaPacientes.agregarListaEspera(nuevoPaciente);
        if (jRadioButtonPrioridadVerde.isSelected()||jRadioButtonPrioridadAmarillo.isSelected()){
           if (this.urgencias.getTipo().equals("Heap")){
               
                this.urgencias.getEstructura1().create(nuevoPaciente);
                System.out.println("Sirve insertar heap en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.urgencias.getEstructura1().toString());
                
          } if (this.urgencias.getTipo().equals("Cola")){
              if (jRadioButtonPrioridadVerde.isSelected()){
                  this.urgencias.getEstructura2().insertar(nuevoPaciente, 0);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.urgencias.getEstructura2().toString());
              }if (jRadioButtonPrioridadAmarillo.isSelected()){
                  this.urgencias.getEstructura2().insertar(nuevoPaciente, 1);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.urgencias.getEstructura2().toString());
              }
              if (jRadioButtonPrioridadRojo.isSelected()){
                  this.urgencias.getEstructura2().insertar(nuevoPaciente, 2);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.urgencias.getEstructura2().toString());
              }
              
              
          }
                
                
        }else if (jRadioButtonPrioridadRojo.isSelected()){
            if (this.emergencias.getTipo().equals("Heap")){
                this.emergencias.getEstructura1().create(nuevoPaciente);
                System.out.println("Sirve insertar heap en Emergencias"+nuevoPaciente.toString());
                System.out.println(this.emergencias.getEstructura1().toString());
            } if (this.emergencias.getTipo().equals("Cola")){
                if (jRadioButtonPrioridadVerde.isSelected()){
                  this.emergencias.getEstructura2().insertar(nuevoPaciente, 0);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.emergencias.getEstructura2().toString());
              }if (jRadioButtonPrioridadAmarillo.isSelected()){
                  this.emergencias.getEstructura2().insertar(nuevoPaciente, 1);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.emergencias.getEstructura2().toString());
              }
              if (jRadioButtonPrioridadRojo.isSelected()){
                  this.emergencias.getEstructura2().insertar(nuevoPaciente, 2);
                System.out.println("Sirve insertar cola prioridad en Urgencias"+nuevoPaciente.toString());
                System.out.println(this.emergencias.getEstructura2().toString());
              }  
        }}
        
     
        this.jTextFieldNombrePaciente.setText("");
        this.jTextFieldNacimientoPaciente.setText("");
        this.jTextFieldDetallePadePaciente.setText("");
        this.buttonGroupTipoPadecimiento.clearSelection();
        this.buttonGroupPrioridadColores.clearSelection();
        this.jLabelNumeroUrgencias.setText(Integer.toString(numeroUrgencias));
        this.jLabelNumerosEmergencias.setText(Integer.toString(numeroEmergencias));
        
        
    }//GEN-LAST:event_jButtonRegistrarsePacienteActionPerformed

    private void jRadioButtonPrioridadRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrioridadRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPrioridadRojoActionPerformed

    public JTable getjTableListaEspera() {
        return jTableListaEspera;
    }
    
    
    public void actualizarTablaUrgencias() {
        if (this.urgencias.getListaVentanillas().esVacia()) {
            ModeladorTablas.vaciarTabla(jTablePacientesUrgencias);
        } else {
            ModeladorTablas.vaciarTabla(jTablePacientesUrgencias);
            Object[] filaNueva;
            NodoS<ModuloUrgencias> temp = this.urgencias.getListaVentanillas().getCabeza();
            for (int i = 0; i < this.urgencias.getListaVentanillas().getTamano(); i++) {
                filaNueva = new Object[]{temp.getContiene().getNombreModulo(),temp.getContiene().getNumModulo(),temp.getContiene().isEstatus()};
                ModeladorTablas.nuevaFila(jTablePacientesUrgencias, filaNueva);
                temp = temp.getSiguiente();
            }

        }
    }
    public void actualizarTablaEmergencias() {
        if (this.emergencias.getListaVentanillas().esVacia()) {
            ModeladorTablas.vaciarTabla(jTablePacientesEmergencias);
        } else {
            ModeladorTablas.vaciarTabla(jTablePacientesEmergencias);
            Object[] filaNueva;
            NodoS<ModuloEmergencias> temp = this.emergencias.getListaVentanillas().getCabeza();
            for (int i = 0; i < this.emergencias.getListaVentanillas().getTamano(); i++) {
                filaNueva = new Object[]{temp.getContiene().getNombreModulo(),temp.getContiene().getNumModulo(),temp.getContiene().isEstatus()};
                ModeladorTablas.nuevaFila(jTablePacientesEmergencias, filaNueva);
                temp = temp.getSiguiente();
            }

        }
    }

   

    public void setjTableListaEspera(JTable jTableListaEspera) {
        this.jTableListaEspera = jTableListaEspera;
    }

    public JTable getjTablePacientesEmergencias() {
        return jTablePacientesEmergencias;
    }

    public void setjTablePacientesEmergencias(JTable jTablePacientesEmergencias) {
        this.jTablePacientesEmergencias = jTablePacientesEmergencias;
    }

    public JTable getjTablePacientesUrgencias() {
        return jTablePacientesUrgencias;
    }

    public void setjTablePacientesUrgencias(JTable jTablePacientesUrgencias) {
        this.jTablePacientesUrgencias = jTablePacientesUrgencias;
    }

    public JTable getjTableEgresos() {
        return jTableEgresos;
    }

    public void setjTableEgresos(JTable jTableEgresos) {
        this.jTableEgresos = jTableEgresos;
    }

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPrioridadColores;
    private javax.swing.ButtonGroup buttonGroupTipoPadecimiento;
    private javax.swing.JButton jButtonAtenderEmergencias;
    private javax.swing.JButton jButtonAtenderUrgencias;
    private javax.swing.JButton jButtonLiberarAtenderEmergencias;
    private javax.swing.JButton jButtonLiberarAtenderUrgencias;
    private javax.swing.JButton jButtonModificarEgresos;
    private javax.swing.JButton jButtonModificarEmergencias;
    private javax.swing.JButton jButtonModificarUrgencias;
    private javax.swing.JButton jButtonRegistrarsePaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNumeroUrgencias;
    private javax.swing.JLabel jLabelNumerosEmergencias;
    private javax.swing.JRadioButton jRadioButtonEstomacalPaciente;
    private javax.swing.JRadioButton jRadioButtonInfartoPaciente;
    private javax.swing.JRadioButton jRadioButtonOtroPaciente;
    private javax.swing.JRadioButton jRadioButtonPartoPaciente;
    private javax.swing.JRadioButton jRadioButtonPrioridadAmarillo;
    private javax.swing.JRadioButton jRadioButtonPrioridadRojo;
    private javax.swing.JRadioButton jRadioButtonPrioridadVerde;
    private javax.swing.JRadioButton jRadioButtonPérdidasangrePaciente;
    private javax.swing.JRadioButton jRadioButtonQuebraduraPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableEgresos;
    private javax.swing.JTable jTableListaEspera;
    private javax.swing.JTable jTablePacientesEmergencias;
    private javax.swing.JTable jTablePacientesUrgencias;
    private javax.swing.JTextField jTextFieldDetallePadePaciente;
    private javax.swing.JTextField jTextFieldNacimientoPaciente;
    private javax.swing.JTextField jTextFieldNombrePaciente;
    private javax.swing.JTextField jTextFieldNumeroModificarConsultorios;
    private javax.swing.JTextField jTextFieldNumeroModificarConsultoriosEmergencias;
    private javax.swing.JTextField jTextFieldNumeroModificarConsultoriosUrgencias;
    // End of variables declaration//GEN-END:variables
}
